spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/security_JWT_exam__test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: rladmswjd803
  jpa:
    hibernate:
      ddl-auto: create